export const INIT_START_GAME = "INIT_START_GAME";
export const START_GAME = "START_GAME";
export const TOTAL_QUESTIONS_SELECTED = "TOTAL_QUESTIONS_SELECTED";
export const ANSWER_SELECTED = "ANSWER_SELECTED";
export const CORRECT_ANSWER_SELECTED = "CORRECT_ANSWER_SELECTED";
export const WRONG_ANSWER_SELECTED = "WRONG_ANSWER_SELECTED";
export const RESET_GAME = "RESET_GAME";
export const TECHNOLOGY_CHECKED = "TECHNOLOGY_CHECKED";
