export const START_GAME = "START_GAME";
export const LOAD_WELCOME_SCREEN = "LOAD_WELCOME_SCREEN";
export const TOTAL_QUESTIONS_SELECTED = "TOTAL_QUESTIONS_SELECTED";
export const ANSWER_SELECTED = "ANSWER_SELECTED";
export const RESET_GAME = "RESET_GAME";
export const TECHNOLOGY_CHECKED = "TECHNOLOGY_CHECKED";
